create table applicaties (id serial, pakket varchar(255), module varchar(255), beschrijving varchar(255), extern bit not null, acceptabel bit not null, administratief bit not null, geodata bit not null, taal varchar(255), spatial_koppeling varchar(255), db_koppeling varchar(255), webbased bit not null, gps bit not null, crow bit not null, opmerking varchar(255), leverancier integer, primary key (id));
create table clusters (id serial, naam varchar(255), omschrijving varchar(255), parent integer, primary key (id));
create table functie_items (id serial, label varchar(255), omschrijving varchar(255), eenheid varchar(255), voorbeelden varchar(255), invoer bit not null, uitvoer bit not null, functie integer, primary key (id));
create table leveranciers (id serial, naam varchar(255), pakket varchar(255), telefoon1 varchar(255), contact varchar(255), telefoon2 varchar(255), telefoon3 varchar(255), email varchar(255), info bit not null, opmerkingen varchar(255), primary key (id));
create table locatie_aanduidingen (id serial, naam varchar(255), omschrijving varchar(255), primary key (id));
create table medewerkers (id serial, achternaam varchar(255), voornaam varchar(255), telefoon varchar(255), functie varchar(255), locatie varchar(255), email varchar(255), primary key (id));
create table moscow (id serial, code varchar(255), naam varchar(255), omschrijving varchar(255), primary key (id));
create table object_typen (id serial, naam varchar(255), primary key (id));
create table onderdeel (id serial, naam varchar(255), omschrijving varchar(255), locatie varchar(255), regio bit not null, primary key (id));
create table onderdeel_medewerkers (id serial, medewerker integer, onderdeel integer, vertegenwoordiger bit not null, primary key (id));
create table rollen (id serial, naam varchar(255), primary key (id));
create table thema_applicaties (id serial, thema integer, applicatie integer, ingebruik bit not null, geodata bit not null, administratief bit not null, voorkeur bit not null, definitief bit not null, standaard bit not null, primary key (id));
create table thema_functies (id serial, naam varchar(255), omschrijving varchar(255), thema integer, applicatie integer, protocol varchar(255), primary key (id));
create table thema_data (id serial, label varchar(255), eenheid varchar(255), omschrijving varchar(255), basisregel bit not null, voorbeelden varchar(255), kolombreedte integer not null, thema integer, moscow integer, waarde_type integer, url VARCHAR(255), kolomnaam VARCHAR(255), primary key (id));
create table thema_verantwoordelijkheden (id serial, thema integer, medewerker integer, onderdeel integer, rol integer, huidige_situatie bit not null, gewenste_situatie bit not null, primary key (id));
create table themas (id serial, code varchar(255), naam varchar(255), moscow integer, belangnr integer not null, cluster integer not null, opmerkingen text, analyse_thema bit not null, locatie_thema bit not null, admin_tabel_opmerkingen text, admin_tabel VARCHAR(255), admin_pk VARCHAR(255), admin_pk_complex BIT DEFAULT '0', admin_spatial_ref VARCHAR(255), admin_query VARCHAR(255), spatial_tabel_opmerkingen text,  spatial_tabel VARCHAR(255), spatial_pk VARCHAR(255), spatial_pk_complex BIT DEFAULT '0', spatial_admin_ref VARCHAR(255), primary key (id));
create table waarde_typen (id serial, naam varchar(255), primary key (id));
create table workshop_medewerkers (id serial, workshop integer, medewerker integer, aanwezig bit not null, primary key (id));
create table workshops (id serial, volgnr integer not null, naam varchar(255), primary key (id));

alter table applicaties add foreign key  (leverancier) references leveranciers (id);
alter table clusters add foreign key  (parent) references clusters (id);
alter table functie_items add foreign key  (functie) references thema_functies (id);
alter table onderdeel_medewerkers add foreign key  (medewerker) references medewerkers (id);
alter table onderdeel_medewerkers add foreign key  (onderdeel) references onderdeel (id);
alter table thema_applicaties add foreign key  (thema) references themas (id);
alter table thema_applicaties add foreign key  (applicatie) references applicaties (id);
alter table thema_functies add foreign key  (thema) references themas (id);
alter table thema_functies add foreign key  (applicatie) references applicaties (id);
alter table thema_data add foreign key  (waarde_type) references waarde_typen (id);
alter table thema_data add foreign key  (thema) references themas (id);
alter table thema_data add foreign key  (moscow) references moscow (id);
alter table thema_verantwoordelijkheden add foreign key  (medewerker) references medewerkers (id);
alter table thema_verantwoordelijkheden add foreign key  (rol) references rollen (id);
alter table thema_verantwoordelijkheden add foreign key  (thema) references themas (id);
alter table thema_verantwoordelijkheden add foreign key  (onderdeel) references onderdeel (id);
alter table themas add foreign key  (cluster) references clusters (id);
alter table themas add foreign key  (moscow) references moscow (id);
alter table workshop_medewerkers add foreign key  (workshop) references workshops (id);
alter table workshop_medewerkers add foreign key  (medewerker) references medewerkers (id);

