-- De 3 views zijn nodig omdat niet alle dtb data getoond moet worden in de data preferred laag. Deze views worden gebruikt in mapserver.

create view dtb_lines_preferred as
SELECT d.oid, d.igds_class, d.igds_style, d.igds_weight, d.igds_color, d.igds_graphic_group, d.igds_level, d.igds_color_blue, d.igds_color_green, d.igds_color_red, d.igds_fill_color, d.igds_fill_color_blue, d.igds_fill_color_green, d.igds_fill_color_red, d.igds_level_comment, d.igds_level_group_id, d.igds_level_name, d.igds_rotation, d.the_geom
   FROM dtb_lines d
  WHERE d.igds_level_name::text = 1101::text OR d.igds_level_name::text = 1102::text OR d.igds_level_name::text = 1103::text OR d.igds_level_name::text = 1104::text OR d.igds_level_name::text = 1105::text OR d.igds_level_name::text = 1106::text OR d.igds_level_name::text = 1107::text OR d.igds_level_name::text = 1108::text OR d.igds_level_name::text = 1109::text OR d.igds_level_name::text = 1110::text OR d.igds_level_name::text = 1111::text OR d.igds_level_name::text = 1112::text OR d.igds_level_name::text = 1113::text OR d.igds_level_name::text = 1114::text OR d.igds_level_name::text = 1201::text OR d.igds_level_name::text = 1202::text OR d.igds_level_name::text = 1301::text OR d.igds_level_name::text = 1304::text OR d.igds_level_name::text = 1305::text OR d.igds_level_name::text = 1306::text OR d.igds_level_name::text = 1402::text OR d.igds_level_name::text = 1403::text OR d.igds_level_name::text = 1404::text OR d.igds_level_name::text = 1501::text OR d.igds_level_name::text = 1601::text OR d.igds_level_name::text = 1603::text OR d.igds_level_name::text = 1604::text OR d.igds_level_name::text = 2004::text OR d.igds_level_name::text = 2005::text OR d.igds_level_name::text = 2011::text OR d.igds_level_name::text = 3601::text OR d.igds_level_name::text = 3602::text OR d.igds_level_name::text = 3603::text OR d.igds_level_name::text = 3604::text OR d.igds_level_name::text = 3605::text OR d.igds_level_name::text = 4901::text;
  
create view dtb_points_preferred as
SELECT d.oid, d.igds_class, d.igds_style, d.igds_weight, d.igds_color, d.igds_graphic_group, d.igds_level, d.igds_color_blue, d.igds_color_green, d.igds_color_red, d.igds_fill_color, d.igds_fill_color_blue, d.igds_fill_color_green, d.igds_fill_color_red, d.igds_level_comment, d.igds_level_group_id, d.igds_level_name, d.igds_rotation, d.the_geom
	FROM dtb_points d
	WHERE d.igds_level_name::text = 1101::text OR d.igds_level_name::text = 1102::text OR d.igds_level_name::text = 1103::text OR d.igds_level_name::text = 1104::text OR d.igds_level_name::text = 1105::text OR d.igds_level_name::text = 1106::text OR d.igds_level_name::text = 1107::text OR d.igds_level_name::text = 1108::text OR d.igds_level_name::text = 1109::text OR d.igds_level_name::text = 1110::text OR d.igds_level_name::text = 1111::text OR d.igds_level_name::text = 1112::text OR d.igds_level_name::text = 1113::text OR d.igds_level_name::text = 1114::text OR d.igds_level_name::text = 1201::text OR d.igds_level_name::text = 1202::text OR d.igds_level_name::text = 1301::text OR d.igds_level_name::text = 1304::text OR d.igds_level_name::text = 1305::text OR d.igds_level_name::text = 1306::text OR d.igds_level_name::text = 1402::text OR d.igds_level_name::text = 1403::text OR d.igds_level_name::text = 1404::text OR d.igds_level_name::text = 1501::text OR d.igds_level_name::text = 1601::text OR d.igds_level_name::text = 1603::text OR d.igds_level_name::text = 1604::text OR d.igds_level_name::text = 2004::text OR d.igds_level_name::text = 2005::text OR d.igds_level_name::text = 2011::text OR d.igds_level_name::text = 3601::text OR d.igds_level_name::text = 3602::text OR d.igds_level_name::text = 3603::text OR d.igds_level_name::text = 3604::text OR d.igds_level_name::text = 3605::text OR d.igds_level_name::text = 4901::text;

create view dtb_polygons_preferred as
SELECT d.oid, d.igds_class, d.igds_style, d.igds_weight, d.igds_color, d.igds_graphic_group, d.igds_level, d.igds_color_blue, d.igds_color_green, d.igds_color_red, d.igds_fill_color, d.igds_fill_color_blue, d.igds_fill_color_green, d.igds_fill_color_red, d.igds_level_comment, d.igds_level_group_id, d.igds_level_name, d.igds_rotation, d.the_geom
	FROM dtb_polygons d
	WHERE d.igds_level_name::text = 1101::text OR d.igds_level_name::text = 1102::text OR d.igds_level_name::text = 1103::text OR d.igds_level_name::text = 1104::text OR d.igds_level_name::text = 1105::text OR d.igds_level_name::text = 1106::text OR d.igds_level_name::text = 1107::text OR d.igds_level_name::text = 1108::text OR d.igds_level_name::text = 1109::text OR d.igds_level_name::text = 1110::text OR d.igds_level_name::text = 1111::text OR d.igds_level_name::text = 1112::text OR d.igds_level_name::text = 1113::text OR d.igds_level_name::text = 1114::text OR d.igds_level_name::text = 1201::text OR d.igds_level_name::text = 1202::text OR d.igds_level_name::text = 1301::text OR d.igds_level_name::text = 1304::text OR d.igds_level_name::text = 1305::text OR d.igds_level_name::text = 1306::text OR d.igds_level_name::text = 1402::text OR d.igds_level_name::text = 1403::text OR d.igds_level_name::text = 1404::text OR d.igds_level_name::text = 1501::text OR d.igds_level_name::text = 1601::text OR d.igds_level_name::text = 1603::text OR d.igds_level_name::text = 1604::text OR d.igds_level_name::text = 2004::text OR d.igds_level_name::text = 2005::text OR d.igds_level_name::text = 2011::text OR d.igds_level_name::text = 3601::text OR d.igds_level_name::text = 3602::text OR d.igds_level_name::text = 3603::text OR d.igds_level_name::text = 3604::text OR d.igds_level_name::text = 3605::text OR d.igds_level_name::text = 4901::text;